//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AttendanceTables = new HashSet<AttendanceTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.SchoolLeavingTables = new HashSet<SchoolLeavingTable>();
            this.StudentPromotTables = new HashSet<StudentPromotTable>();
            this.SubmissionFeeTables = new HashSet<SubmissionFeeTable>();
        }
    
        public int StudentID { get; set; }
        [Required(ErrorMessage ="Please Select Session")]
        public int SessionID { get; set; }
        [Required(ErrorMessage = "Please Select Programe")]
        public int ProgrameID { get; set; }
        [Required(ErrorMessage = "Please Select Current Class")]
        public int ClassID { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please Enter Student Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Father Name")]
        public string FatherName { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DateofBirth { get; set; }
        [Required(ErrorMessage = "Please Enter Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter Contact No")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "Please Enter Student CNIC")]
        public string CNIC { get; set; }
        [Required(ErrorMessage = "Please Enter Father CNIC")]
        public string FNIC { get; set; }
        public string Photo { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please Select Addmission Date")]
        public System.DateTime AddmissionDate { get; set; }
        [Required(ErrorMessage = "Please Enter Previous School Name")]
        public string PreviousSchool { get; set; }
        [Required(ErrorMessage = "Please Enter Previous Percentage")]
        public Nullable<double> PreviousPercentage { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please Enter Email Address")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Please Enter Permanent Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter Nationality")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "Please Enter Religion")]
        public string Religion { get; set; }
        [Required(ErrorMessage = "Please Enter Caste")]
        public string TribeorCaste { get; set; }
        [Required(ErrorMessage = "Please Enter Father Occupational")]
        public string FatherGuardiansOccupation { get; set; }
        [Required(ErrorMessage = "Please Enter Postal Address")]
        public string FatherGuardiansPostalAddress { get; set; }
        [Required(ErrorMessage = "Please Enter Office Phone No.")]
        public string PhoneOffice { get; set; }
        [Required(ErrorMessage = "Please Enter Home Phone No.")]
        public string PhoneResident { get; set; }
        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTable> AttendanceTables { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPromotTable> StudentPromotTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFeeTable> SubmissionFeeTables { get; set; }
    }
}
